artist:
  name: Your
  tagline: Acid Wash Electronic Acid Music
  seo_title: "Acid Wash | Electronic Acid Music | San Antonio, TX"
  seo_description: "Acid Wash is an Electronic Music Group based out of San Antonio, TX. Acid Wash is comprised of John Nap, Man Alone, and The Engineer"
  # contact_twitter_username:
  # contact_phone: 
  # contact_email: 

social:
  # - name: Facebook
  #   url: https://facebook.com
  - name: Instagram
    url: https://instagram.com/acid.wash_/
  # - name: Twitter
  #   url: https://twitter.com
  # - name: Youtube
  #   url: https://youtube.com
  - name: Bandcamp
    url: https://acidwashmusic.bandcamp.com

site_language: en
